### ISSUE TITLE
Always getting a request error when using this github action

### ISSUE THREAD

**Issue by labboy0276** [HosniD/transfer-issue#37]
Hello

I have tried multiple versions of this github action and no matter what I try I always get this RequestError:

The source and destination repos definitely exist.  Here is a link to one of the failed [Github Actions](https://github.com/thinktandem/issue-trill/actions/runs/1317287962)

Here is an error we always get:

```
error RequestError [HttpError]: Not Found
      at /home/runner/work/_actions/HosniD/transfer-issue/v0.1.6/webpack:/javascript-action/node_modules/@octokit/request/dist-node/index.js:86:1
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at run (/home/runner/work/_actions/HosniD/transfer-issue/v0.1.6/webpack:/javascript-action/index.js:71:1) {
    name: 'HttpError',
    status: 404,
    response: {
      url: 'https://api.github.com/repos/thinktandem/tandem/issues',
      status: 404,
      headers: {
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
        connection: 'close',
        'content-encoding': 'gzip',
        'content-security-policy': "default-src 'none'",
        'content-type': 'application/json; charset=utf-8',
        date: 'Thu, 07 Oct 2021 17:47:04 GMT',
        'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
        server: 'GitHub.com',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
        'transfer-encoding': 'chunked',
        vary: 'Accept-Encoding, Accept, X-Requested-With',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'deny',
        'x-github-media-type': 'github.v3; format=json',
        'x-github-request-id': '0407:2081:C740A:1B3DCF:615F3298',
        'x-ratelimit-limit': '60',
        'x-ratelimit-remaining': '59',
        'x-ratelimit-reset': '1633632424',
        'x-ratelimit-resource': 'core',
        'x-ratelimit-used': '1',
        'x-xss-protection': '0'
      },
      data: {
        message: 'Not Found',
        documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue'
      }
    },
    request: {
      method: 'POST',
      url: 'https://api.github.com/repos/thinktandem/tandem/issues',
      headers: {
        accept: 'application/vnd.github.v3+json',
        'user-agent': 'octokit-rest.js/18.9.0 octokit-core.js/3.5.1 Node.js/12.13.1 (linux; x64)',
        'content-type': 'application/json; charset=utf-8'
      },
      body: '{"title":"asd","body":"Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!\\r\\n\\r\\n**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.\\r\\n\\r\\nPlease complete the following steps.\\r\\n\\r\\n**The more steps you complete the more likely we are to address your issue!**\\r\\n\\r\\n1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn\'t fixed already.\\r\\n2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.\\r\\n\\r\\nThe **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.\\r\\n\\r\\nIf you are not sure how to do that then please complete as much of the below section as possible\\r\\n\\r\\n**Tell us about your setup**\\r\\n\\r\\nWhat is your lando version and operating system? **(note that the older your version the less likely we are to reply)**\\r\\n\\r\\n*Example: v3.0.0-rc.2 on Windows 10 Professional*\\r\\n\\r\\n**Tell us about your `.lando.yml`**\\r\\n\\r\\nPaste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.\\r\\n\\r\\n*Example:*\\r\\n\\r\\n```yml\\r\\nname: lamp2\\r\\nrecipe: lamp\\r\\nconfig:\\r\\n  php: \'5.6\'\\r\\n  webroot: www\\r\\n  database: mysql\\r\\n  xdebug: true\\r\\n```\\r\\n\\r\\nIt is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.\\r\\n\\r\\n**Tell us about the command you were running**\\r\\n\\r\\nPaste in a series of commands that caused the bug.\\r\\n\\r\\n*Example:*\\r\\n\\r\\n```bash\\r\\nlando init --sourcer remote --recipe lamp --webroot web\\r\\nlando start\\r\\n# Edited my lando.yml as above\\r\\nlando rebuild -y\\r\\n```\\r\\n\\r\\n**Tell us about the error you got**\\r\\n\\r\\nRerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.\\r\\n\\r\\n*Example:*\\r\\n\\r\\n```bash\\r\\nlando php -e \\"phpinfo();\\" -vvvv\\r\\n```\\r\\n\\r\\n**Tell us generally about your bug**\\r\\n\\r\\n*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*\\r\\n\\r\\nPlease detail the steps we can take to replicate this bug. Be as detailed as possible.\\r\\n\\r\\n*Example:*\\r\\n\\r\\n```bash\\r\\n1. Started up GUI\\r\\n2. Clicked on my Pantheon account in the sidebar\\r\\n3. Selected a site and an environment\\r\\n4. Kept the default create options and pressed submit\\r\\n```\\r\\n\\r\\n**Tell us more**\\r\\n\\r\\nCould better documentation have prevented this issue? if so what should we change?\\r\\nDoes this bug prevent you from using lando?\\r\\n\\n          link: https://github.com/thinktandem/issue-trill/issues/4","labels":["support-bot"]}',
      request: { hook: [Function: bound bound register] }
    }
  }
  Error: Not Found
```

**Comment by labboy0276** [comment]
We just built our own github actions to handle our stuffs
